apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webserver
spec:
  replicas: 10
  selector:
    matchLevels:
      app: webfront
    template:
      metadata:
        labels:
          app: webfront
        spec:
      containers:
      - image: nginx
        name: webfront-container
        ports:
          - containerPorts: 80
